# 下载参数配置
downloader:
  proxy: http://192.168.5.44:7897 # 下載代理
  worker: 5 # 最大的同时下载任务数
  source: apkpure # 下載來源 目前只有apkpure可选
  timeout: 500 # 下载超时时间 单位s
  max-retry: 1  # 下载最大重试次数
  save-path: ./download # 本地存储路径
  limit-size: 200 # 文件大小限制 单位M
  upload-enabled: true # 是否上传到对象存储，目前只支持上传到minio，上传后本地文件会被删除
# 静态分析配置
static-analyzer:
  use: jadx
  exec: D:\GreenSoftware\jadx-1.5.1\bin\jadx.bat # 可执行程序路径
  worker: 2 # 最大的同时下载任务数
  workdir: ./analysis
